### ISSUE TITLE
Inject xposed plugin success.但是无效果

### ISSUE THREAD

**Issue by df13954** [WindySha/Poros#1]
aosp12，编写了一个靶子apk，一个test函数返回字符串，Xposed插件hook这个test函数修改成固定的字符串。
1、使用lsp加载插件，可以成功hook test。卸载lsp，重启手机。
2、使用./start.sh -p com.test -f xxxx.apk
Inject xposed plugin success.
点击按钮触发test，无效果。

---

现在我的测试流程有没有问题？是这样去注入测试吗。
如果是错误的，应该如何修正呢

**Comment by WindySha** [comment]
提供下插件apk文件以及源码中的核心代码？

**Comment by df13954** [comment]
> 提供下插件apk文件以及源码中的核心代码？

链接: https://pan.baidu.com/s/1324KFZeGTLbRkh3FNlH56Q?pwd=f67e 提取码: f67e 
com.shocker.mincore.MainActivity -> 

```
private String test() {
    int i = new Random().nextInt(100);
    return "age:" + i;
}
```

xp模块hook这个函数，返回了param.setResult("xposed hook");

**Comment by WindySha** [comment]
我在google pixel pro7  android13机型上测试没有问题，可以弹出toast "xposed hook"。
假如xposed插件加载了，也就说
        Log.e(TAG, "handleLoadPackage: 开始hook了");
这个日志打印出来了，但toast没有弹对，可能是hook框架的兼容性问题，尝试Hook其他函数试试，尝试换个机型试试

**Comment by df13954** [comment]
> 我在google pixel pro7 android13机型上测试没有问题，可以弹出toast "xposed hook"。 假如xposed插件加载了，也就说 Log.e(TAG, "handleLoadPackage: 开始hook了"); 这个日志打印出来了，但toast没有弹对，可能是hook框架的兼容性问题，尝试Hook其他函数试试，尝试换个机型试试
这个handleLoadPackage: 开始hook了日志也没有出现。我明天找个android13的试试。

**Comment by df13954** [comment]
在pixel6-Android13上成功hook了

**Comment by WindySha** [comment]
> 在pixel6-Android13上成功hook了

失败的是哪个机型，哪个android版本，可能是SandHook库的有bug，我抽空看看能不能修
